Repository Hyp-ed/hyped-2023, pull requests merged in 2022-10, with the labels that each got.

#7 Fix Mac Build
  lib/core/time.hpp
  lib/core/wall_clock.cpp
  lib/utils/manual_time.cpp
  test/utils/manual_time.cpp
Labels: build-system, moderate

#8 MTC - Inital setup
  lib/CMakeLists.txt
  lib/core/types.hpp
  lib/io/can.cpp
  lib/io/can.hpp
  lib/motorcontrollers/CMakeLists.txt
  lib/motorcontrollers/can_processor.cpp
  lib/motorcontrollers/can_processor.hpp
  lib/motorcontrollers/controller.cpp
  lib/motorcontrollers/controller.hpp
  lib/motorcontrollers/main.cpp
  lib/motorcontrollers/main.hpp
  lib/motorcontrollers/messages.hpp
  lib/motorcontrollers/state_processor.cpp
  lib/motorcontrollers/state_processor.hpp
Labels: motor-controllers

#4 NAV - Basic navigation simulator
  .clang-format
  CODEOWNERS
  README.md
  lib/CMakeLists.txt
  lib/core/types.hpp
  lib/navigation/CMakeLists.txt
  lib/navigation/kalman_filter.cpp
  lib/navigation/kalman_filter.hpp
  lib/navigation/navigator.hpp
  lib/utils/manual_time.hpp
  lib/utils/naive_navigator.cpp
  lib/utils/naive_navigator.hpp
  test/CMakeLists.txt
  test/navigation/CMakeLists.txt
  test/navigation/kalman_filter.cpp
  test/navigation/navigation.cpp
  test/utils/manual_time.cpp
  test/utils/naive_navigator.cpp
Labels: navigation

#6 SNS - ADC
  lib/io/adc.cpp
  lib/io/adc.hpp
Labels: sensors, moderate

#9 SNS - I2C
  lib/io/i2c.cpp
  lib/io/i2c.hpp
Labels: sensors

#15 SNS - ADC Logging
  lib/io/adc.cpp
  lib/io/adc.hpp
Labels: sensors
